package com.example.neuekaroly.ehubsharing.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_CUSTOMERS_WITH_CHARGER_POINTS".
*/
public class JoinCustomersWithChargerPointsDao extends AbstractDao<JoinCustomersWithChargerPoints, Long> {

    public static final String TABLENAME = "JOIN_CUSTOMERS_WITH_CHARGER_POINTS";

    /**
     * Properties of entity JoinCustomersWithChargerPoints.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ChargerPointId = new Property(1, Long.class, "chargerPointId", false, "CHARGER_POINT_ID");
        public final static Property CustomerId = new Property(2, Long.class, "customerId", false, "CUSTOMER_ID");
    }


    public JoinCustomersWithChargerPointsDao(DaoConfig config) {
        super(config);
    }
    
    public JoinCustomersWithChargerPointsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_CUSTOMERS_WITH_CHARGER_POINTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CHARGER_POINT_ID\" INTEGER," + // 1: chargerPointId
                "\"CUSTOMER_ID\" INTEGER);"); // 2: customerId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_CUSTOMERS_WITH_CHARGER_POINTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinCustomersWithChargerPoints entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long chargerPointId = entity.getChargerPointId();
        if (chargerPointId != null) {
            stmt.bindLong(2, chargerPointId);
        }
 
        Long customerId = entity.getCustomerId();
        if (customerId != null) {
            stmt.bindLong(3, customerId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinCustomersWithChargerPoints entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long chargerPointId = entity.getChargerPointId();
        if (chargerPointId != null) {
            stmt.bindLong(2, chargerPointId);
        }
 
        Long customerId = entity.getCustomerId();
        if (customerId != null) {
            stmt.bindLong(3, customerId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinCustomersWithChargerPoints readEntity(Cursor cursor, int offset) {
        JoinCustomersWithChargerPoints entity = new JoinCustomersWithChargerPoints( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // chargerPointId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // customerId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinCustomersWithChargerPoints entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setChargerPointId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCustomerId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinCustomersWithChargerPoints entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinCustomersWithChargerPoints entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinCustomersWithChargerPoints entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
