package database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import database.ChargerPoint;

import database.ChargerPointDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chargerPointDaoConfig;

    private final ChargerPointDao chargerPointDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chargerPointDaoConfig = daoConfigMap.get(ChargerPointDao.class).clone();
        chargerPointDaoConfig.initIdentityScope(type);

        chargerPointDao = new ChargerPointDao(chargerPointDaoConfig, this);

        registerDao(ChargerPoint.class, chargerPointDao);
    }
    
    public void clear() {
        chargerPointDaoConfig.clearIdentityScope();
    }

    public ChargerPointDao getChargerPointDao() {
        return chargerPointDao;
    }

}
